FROM debian:stable-slim
LABEL org.opencontainers.image.authors="Fukumen <fukumen@gmail.com>" \
    org.opencontainers.image.source="https://github.com/fukumen/p2-php"

ARG DEB_NAME
ARG DEBIAN_VERSION
ARG PHP_VERSION_FULL
ARG CADDY_VERSION_FULL
ARG COMPOSER_VERSION_FULL
ARG REPO_HASH
ARG REPO_LOG
ARG RUN_ID
ARG RUN_NUMBER
ENV VER_PHP=$PHP_VERSION_FULL
ENV VER_DEBIAN=$DEBIAN_VERSION
ENV VER_CADDY=$CADDY_VERSION_FULL
ENV VER_COMPOSER=$COMPOSER_VERSION_FULL
ENV VER_REPO_HASH=$REPO_HASH
ENV VER_REPO_LOG=$REPO_LOG
ENV VER_RUN_ID=$RUN_ID
ENV VER_RUN_NUMBER=$RUN_NUMBER
ENV VER_BUILD_TYPE=aiodeb

COPY --from=aiodeb-dist /${DEB_NAME} /tmp/

RUN set -eux; \
    cp -f "/tmp/${DEB_NAME}" /tmp/install.deb; \
    printf '#!/bin/sh\nexit 0\n' > /usr/sbin/systemctl \
    && chmod 755 /usr/sbin/systemctl \
    && apt-get update \
    && apt-get install -y --no-install-recommends /tmp/install.deb \
    && rm -f /tmp/*.deb /usr/sbin/systemctl \
    && rm -rf /var/lib/apt/lists/*

CMD ["sh", "-c", "exec /opt/rep2-allinone/rep2-allinone"]
