; PHP 本体の既定値と異なる値のみを定義する
memory_limit = 512M
post_max_size = 128M
upload_max_filesize = 128M
display_errors = Off
display_startup_errors = Off
log_errors = On
opcache.jit = tracing
opcache.enable_cli = 1
