[PHP]
memory_limit = 512M
post_max_size = 128M
upload_max_filesize = 128M
display_errors = Off
display_startup_errors = Off
log_errors = On
fastcgi.logging = Off
opcache.jit = tracing
opcache.enable_cli = 1

extension_dir = "ext"

; Core Extensions for rep2 (from composer.json and Dockerfile)
extension=bz2
extension=curl
extension=exif
extension=fileinfo
extension=gd
extension=gettext
extension=intl
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=sqlite3
extension=zip
