name: Daily Version and Update Check

on:
  schedule:
    # UTC 0:00
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Previous Versions Cache
        uses: actions/cache@v4
        with:
          path: scripts/prev_versions.json
          key: php-version-cache-${{ github.run_id }}
          restore-keys: |
            php-version-cache-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Version Checker
        run: python scripts/check_versions.py --fail-on-update --only-on-change
