name: Trigger Docker Build

on:
  push:
    branches:
      - php8-merge-mbstring
    paths-ignore:
      - '**.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: fukumen/docker-rep2
          event-type: p2-php-update
